import enum


class Motivo(enum.Enum):
    INASISTENCIA_DEL_DOCENTE = 'INASISTENCIA DEL DOCENTE'
    FALLA_DE_TRANSPORTE = 'FALLA DE TRANSPORTE'
    EMERGENCIA_DE_SALUD = 'EMERGENCIA DE SALUD'
    CONDICIONES_CLIMATICAS = 'CONDICIONES CLIMÁTICAS'
    AUSENCIA_DE_ESTUDIANTES = 'AUSENCIA DE ESTUDIANTES'
    PROBLEMA_TECNICO = 'PROBLEMA TÉCNICO'
    CIERRE_INSTITUCIONAL = 'CIERRE INSTITUCIONAL'
    FESTIVO_NO_LABORAL = 'FESTIVO NO LABORAL'
    OTRO_MOTIVO = 'OTRO MOTIVO'